class AddKeys < ActiveRecord::Migration
  def change
    add_foreign_key "alerts", "users", name: "alerts_assignee_id_fk", column: "assignee_id"
    add_foreign_key "alerts", "hoas", name: "alerts_hoa_id_fk"
    add_foreign_key "alerts", "users", name: "alerts_user_id_fk"
    add_foreign_key "announcements", "hoas", name: "announcements_hoa_id_fk"
    add_foreign_key "announcements", "users", name: "announcements_user_id_fk"
    add_foreign_key "attachments", "alerts", name: "attachments_alert_id_fk"
    add_foreign_key "collaborations", "users", name: "collaborations_user_id_fk"
    add_foreign_key "comments", "hoas", name: "comments_hoa_id_fk"
    add_foreign_key "comments", "users", name: "comments_user_id_fk"
    add_foreign_key "events", "hoas", name: "events_hoa_id_fk"
    add_foreign_key "events", "users", name: "events_user_id_fk"
    add_foreign_key "homepages", "hoas", name: "homepages_hoa_id_fk"
    add_foreign_key "participations", "events", name: "participations_event_id_fk"
    add_foreign_key "participations", "users", name: "participations_user_id_fk"
    add_foreign_key "payments", "hoas", name: "payments_hoa_id_fk"
    add_foreign_key "payments", "users", name: "payments_user_id_fk"
    add_foreign_key "posts", "hoas", name: "posts_hoa_id_fk"
    add_foreign_key "posts", "users", name: "posts_user_id_fk"
    add_foreign_key "readings", "users", name: "readings_user_id_fk"
    add_foreign_key "support_messages", "hoas", name: "support_messages_hoa_id_fk"
    add_foreign_key "support_messages", "users", name: "support_messages_user_id_fk"
    add_foreign_key "taggings", "tags", name: "taggings_tag_id_fk"
    add_foreign_key "users", "hoas", name: "users_hoa_id_fk"
    add_foreign_key "users_roles", "roles", name: "users_roles_role_id_fk"
    add_foreign_key "users_roles", "users", name: "users_roles_user_id_fk"
  end
end
